### ISSUE TITLE
GMP install on homestead

### ISSUE THREAD

**Issue by ajthinking** [blockavel/lara-block-io#36]
Im having issues installing GMP on my vagrant homestead box (PHP 7.0.13). Is there a failsafe way to go about doing that? Would be a nice addition to the readme. Looking forward to trying this out.

```
vagrant@homestead:~/Code/myapp$ sudo apt-get install php7.0-gmp
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  php7.0-gmp
0 upgraded, 1 newly installed, 0 to remove and 44 not upgraded.
Need to get 20.7 kB of archives.
After this operation, 97.3 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.0-gmp amd64 7.0.13-1+deb.sury.org~xenial+1
  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php7.0/php7.0-gmp_7.0.13-1+deb.sury.org~xenial+1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by alejandro-carstens** [comment]
Hi ajthinking,

Sorry for the inconvenience. Please try the following commands:
sudo apt-get update
sudo apt-get install libgmp-dev
sudo apt-get install php7.0-gmp

You might need to add the following to your php.ini file:
extension=php_gmp.so

Please let me know if you could solve the problem, I will keep the issue open for now.

**Comment by ajthinking** [comment]
Awesome, thanks alot Alejandro, sudo apt-get update did the trick!

**Comment by alejandro-carstens** [comment]
Glad to hear that. Good luck.
